EECS 4312 Course Project, Ricardo Santin-Andrade, 216981789

In [8]:
#Task 1 Code
from google_play_scraper import app
import pandas as pd
import numpy as np

from google_play_scraper import Sort, reviews_all
app_reviews = reviews_all(
    'com.brentpanther.bitcoinwidget',
    sleep_milliseconds=0,
    lang='en',
    sort=Sort.NEWEST
)

df_app = pd.DataFrame(np.array(app_reviews),columns=['review'])

df_app = df_app.join(pd.DataFrame(df_app.pop('review').tolist()))

df_app.to_excel('Simple_Crypto_Widget_Reviews.xlsx')

In [5]:
from google_play_scraper import app
import pandas as pd
import numpy as np 

from google_play_scraper import Sort, reviews_all

app_reviews = reviews_all(
    'com.stock.widget',
    sleep_milliseconds=0, # defaults to 0
    lang='en', # defaults to 'en'
    country='us', # defaults to 'us'
    sort=Sort.NEWEST, # defaults to Sort.MOST_RELEVANT
)

df_app = pd.DataFrame(np.array(app_reviews),columns=['review'])

df_app = df_app.join(pd.DataFrame(df_app.pop('review').tolist()))

df_app.to_excel("Stock_Widget_Reviews.xlsx")

In [4]:
from google_play_scraper import app
import pandas as pd
import numpy as np 

from google_play_scraper import Sort, reviews_all

app_reviews = reviews_all(
    'com.yahoo.mobile.client.android.finance',
    sleep_milliseconds=0, # defaults to 0
    lang='en', # defaults to 'en'
    country='us', # defaults to 'us'
    sort=Sort.NEWEST, # defaults to Sort.MOST_RELEVANT
)

df_app = pd.DataFrame(np.array(app_reviews),columns=['review'])

df_app = df_app.join(pd.DataFrame(df_app.pop('review').tolist()))

df_app.to_excel("Yahoo_Finance_Stock_News.xlsx")

In [116]:
from google_play_scraper import app
import pandas as pd
import numpy as np 

from google_play_scraper import Sort, reviews_all

app_reviews = reviews_all(
    'com.coinmarketcap.android',
    sleep_milliseconds=0, # defaults to 0
    lang='en', # defaults to 'en'
    country='us', # defaults to 'us'
    sort=Sort.NEWEST, # defaults to Sort.MOST_RELEVANT5
)

df_app = pd.DataFrame(np.array(app_reviews),columns=['review'])

df_app = df_app.join(pd.DataFrame(df_app.pop('review').tolist()))

df_app.to_excel("Coin_Market_Cap_Crypto_Tracker.xlsx")

In [129]:
from google_play_scraper import app
import pandas as pd
import numpy as np 

from google_play_scraper import Sort, reviews_all

app_reviews = reviews_all(
    'com.currency.exchange.widgetscrypto',
    sleep_milliseconds=0, # defaults to 0
    lang='en', # defaults to 'en'
    country='us', # defaults to 'us'
    sort=Sort.NEWEST, # defaults to Sort.MOST_RELEVANT5
)

df_app = pd.DataFrame(np.array(app_reviews),columns=['review'])

df_app = df_app.join(pd.DataFrame(df_app.pop('review').tolist()))

df_app.to_excel("Bitcoin_&_Crypto_Price_Widget.xlsx")

INSERT TASK 1 APPENDAGES HERE

In [78]:
#!pip install clean-text
#!pip install inflect
#!pip install num2words
#!pip install nltk

#Task 2
import csv
import pandas as pd
import string
data = pd.read_csv("EECS4312CourseProjectTask1.csv", encoding = 'utf-8')
#print(data.head())

#expanding the dispay of text sms column
#pd.set_option('display.max_colwidth', 1)
#using only v1 and v2 column
#data.Review_Text

#1.remove all punctuation
punct = "\n\r"+string.punctuation
pattern = r'[^\w\s]'
data["Review_Text"] = data["Review_Text"].str.translate(str.maketrans('','',punct))
#print(data.head())



#2.remove all special characters and emojis
def deEmojify(inputString):
    return inputString.encode('ascii', 'ignore').decode('ascii')
    
data["Review_Text"] = data["Review_Text"].apply(lambda s: deEmojify(s))

#https://www.analyticsvidhya.com/blog/2021/08/a-friendly-guide-to-nlp-text-pre-processing-with-python-example/

#3.turn numbers into text
from num2words import num2words
import re

def sep_num_words_func(text):
    '''
    Separates numbers from words or other characters
    
    Args:
        text (str): String to which the function is to be applied, string
    
    Returns:
        Clean string with separated numbers from words or other characters
    ''' 
    return re.sub(r"([0-9]+(\.[0-9]+)?)",r" \1 ", text).strip()
    
def num_to_words(text):
    '''
    Convert Numbers to Words
    
    Args:
        text (str): String to which the function is to be applied, string
    
    Returns:
        Clean string with converted Numbers to Words
    ''' 
    after_spliting = text.split()

    for index in range(len(after_spliting)):
        if after_spliting[index].isdigit():
            after_spliting[index] = num2words(after_spliting[index])
    numbers_to_words = ' '.join(after_spliting)
    return numbers_to_words 

data["Review_Text"] = data["Review_Text"].apply(lambda s: num_to_words(sep_num_words_func(s)))

#https://michael-fuchs-python.netlify.app/2021/06/19/nlp-text-pre-processing-vii-special-cases/

#4.remove extra white spaces
for c in data:
    data[c] = data[c].str.strip()

#5.make all text lowercase
data["Review_Text"] = data["Review_Text"].astype(str).str.lower() 
#print(data.head())

#https://www.reddit.com/r/learnpython/comments/qy6d35/how_to_remove_all_excessive_spaces_in_any_csv/

#6.remove stop words
import nltk
from nltk.corpus import stopwords
stop = stopwords.words('english')


def rem_en(input_text):
    words = input_text.lower().split()
    noise_free_words = [word for word in words if word not in stopwords.words('english')] 
    noise_free_text = " ".join(noise_free_words) 
    return noise_free_text
    
data["Review_Text"] = data["Review_Text"].apply(lambda s: rem_en(s))

#print(data.head())

#https://www.analyticsvidhya.com/blog/2021/08/a-friendly-guide-to-nlp-text-pre-processing-with-python-example/

#7.lemmatize the reviews
import nltk
       
w_tokenizer = nltk.tokenize.WhitespaceTokenizer()
lemmatizer = nltk.stem.WordNetLemmatizer()

def lemmatize_text(text):
    return [lemmatizer.lemmatize(word) for word in w_tokenizer.tokenize(text)]

data["Review_Text"] = data.Review_Text.apply(lemmatize_text)

pd.set_option('display.max_rows', 5000)

print(data.head(15))

data.to_csv('Task2Output.csv', index = False)

#https://stackoverflow.com/questions/47557563/lemmatization-of-all-pandas-cells

                      Package_Name  \
0   com.brentpanther.bitcoinwidget
1   com.brentpanther.bitcoinwidget
2   com.brentpanther.bitcoinwidget
3   com.brentpanther.bitcoinwidget
4   com.brentpanther.bitcoinwidget
5   com.brentpanther.bitcoinwidget
6   com.brentpanther.bitcoinwidget
7   com.brentpanther.bitcoinwidget
8   com.brentpanther.bitcoinwidget
9   com.brentpanther.bitcoinwidget
10  com.brentpanther.bitcoinwidget
11  com.brentpanther.bitcoinwidget
12  com.brentpanther.bitcoinwidget
13  com.brentpanther.bitcoinwidget
14  com.brentpanther.bitcoinwidget

                                          Review_Text
0                          [error, data, coin, gecko]
1                                     [simple, clean]
2   [app, exactly, im, looking, especially, see, m...
3                                              [good]
4             [great, widget, show, currency, wallet]
5                             [best, bitcoin, widget]
6   [simple, yet, brilliant, adjustment, make, loo...
7   [app, personally, easiest, crypto, app, naviga...
8   [like, exactly, described, simple, crypto, wid...
9      [used, good, stopped, working, latest, update]
10  [devs, reply, comment, already, latest, versio...
11                                    [work, awesome]
12  [really, wanted, widget, home, screen, apparen...
13  [solid, app, year, noticing, price, updating, ...
14  [widget, working, correctly, dont, update, pri...

Before

In [73]:
#!pip install textblob

data = pd.read_csv("Task3Input.csv")

from textblob import TextBlob

# The x in the lambda function is a row (because I set axis=1)
# Apply iterates the function accross the dataframe's rows
data['Polarity'] = data.apply(lambda x: TextBlob(x['Review_Text']).sentiment.polarity, axis=1)

#https://stackoverflow.com/questions/35559199/textblob-sentiment-analysis-on-a-csv-file

data.to_csv('Task3TextblobOutput.csv', index = False)

pd.set_option('display.max_rows', 5000)
data.head(1000)

,Package_Name,Review_Text,Polarity
0,com.brentpanther.bitcoinwidget,"['error', 'data', 'coin', 'gecko']",0.000000
1,com.brentpanther.bitcoinwidget,"['simple', 'clean']",0.183333
2,com.brentpanther.bitcoinwidget,"['app', 'exactly', 'im', 'looking', 'especiall...",0.307143
3,com.brentpanther.bitcoinwidget,['good'],0.700000
4,com.brentpanther.bitcoinwidget,"['great', 'widget', 'show', 'currency', 'wallet']",0.800000
5,com.brentpanther.bitcoinwidget,"['best', 'bitcoin', 'widget']",1.000000
6,com.brentpanther.bitcoinwidget,"['simple', 'yet', 'brilliant', 'adjustment', '...",0.392045
7,com.brentpanther.bitcoinwidget,"['app', 'personally', 'easiest', 'crypto', 'ap...",0.358333
8,com.brentpanther.bitcoinwidget,"['like', 'exactly', 'described', 'simple', 'cr...",0.177273
9,com.brentpanther.bitcoinwidget,"['used', 'good', 'stopped', 'working', 'latest...",0.600000
10,com.brentpanther.bitcoinwidget,"['devs', 'reply', 'comment', 'already', 'lates...",0.179167
11,com.brentpanther.bitcoinwidget,"['work', 'awesome']",1.000000
12,com.brentpanther.bitcoinwidget,"['really', 'wanted', 'widget', 'home', 'screen...",0.125000
13,com.brentpanther.bitcoinwidget,"['solid', 'app', 'year', 'noticing', 'price', ...",0.000000
14,com.brentpanther.bitcoinwidget,"['widget', 'working', 'correctly', 'dont', 'up...",0.000000
15,com.brentpanther.bitcoinwidget,['good'],0.700000
16,com.brentpanther.bitcoinwidget,"['ek', 'ek', 'ek', 'ek', 'bot', 'valid', 'revi...",0.000000
17,com.brentpanther.bitcoinwidget,"['real', 'trouble', 'updating', 'price', 'rece...",-0.150000
18,com.brentpanther.bitcoinwidget,"['use', 'every', 'day']",0.000000
19,com.brentpanther.bitcoinwidget,"['simple', 'sexy', 'job', 'pretty', 'well']",0.250000
20,com.brentpanther.bitcoinwidget,"['working', 'want', 'select', 'karlsonthe', 'a...",-0.100000
21,com.brentpanther.bitcoinwidget,"['faster', 'refresh', 'everything', 'wanted']",0.000000
22,com.brentpanther.bitcoinwidget,['great'],0.800000
23,com.brentpanther.bitcoinwidget,"['new', 'update', 'longer', 'place', 'crypto',...",0.318182
24,com.brentpanther.bitcoinwidget,"['good', 'would', 'great', 'could', 'add', 'on...",0.750000
25,com.brentpanther.bitcoinwidget,"['work', 'update', 'price', 'almost', 'week']",0.000000
26,com.brentpanther.bitcoinwidget,"['seems', 'pretty', 'good', 'far', 'one', 'sug...",0.262500
27,com.brentpanther.bitcoinwidget,['nine'],0.000000
28,com.brentpanther.bitcoinwidget,"['far', 'best', 'looking', 'simplest', 'crypto...",0.550000
29,com.brentpanther.bitcoinwidget,['good'],0.700000
30,com.brentpanther.bitcoinwidget,"['app', 'freezez', 'sometimes', 'also', 'funct...",0.000000
31,com.brentpanther.bitcoinwidget,"['work', 'good', 'great', 'keep', 'eye', 'mark...",0.700000
32,com.brentpanther.bitcoinwidget,"['wanted', 'simply', 'stealth', 'update']",0.000000
33,com.brentpanther.bitcoinwidget,"['lovely', 'point', 'exactly', 'needed']",0.375000
34,com.brentpanther.bitcoinwidget,"['say', 'version', 'simple', 'crypto', 'widget...",0.399167
35,com.brentpanther.bitcoinwidget,['good'],0.700000
36,com.brentpanther.bitcoinwidget,"['great', 'app', 'simple', 'useful']",0.366667
37,com.brentpanther.bitcoinwidget,"['top', 'top']",0.500000
38,com.brentpanther.bitcoinwidget,"['hello', 'im', 'deaf', 'please']",0.000000
39,com.brentpanther.bitcoinwidget,"['simple', 'pretty', 'open', 'source']",0.083333
40,com.brentpanther.bitcoinwidget,['great'],0.800000
41,com.brentpanther.bitcoinwidget,"['seems', 'incompatible', 'android', 'six', 'h...",0.533333
42,com.brentpanther.bitcoinwidget,"['everything', 'want', 'perfect']",1.000000
43,com.brentpanther.bitcoinwidget,"['love', 'made', 'little', 'le', 'simple', 'co...",0.185417
44,com.brentpanther.bitcoinwidget,"['need', 'sometimes', 'price', 'dont', 'update...",0.650000
45,com.brentpanther.bitcoinwidget,"['convenient', 'accurate', 'stopped', 'working']",0.400000
46,com.brentpanther.bitcoinwidget,"['great', 'app', 'created', 'widget', 'showing...",0.600000
47,com.brentpanther.bitcoinwidget,"['great', 'app', 'wish', 'add', 'couns']",0.800000
48,com.brentpanther.bitcoinwidget,"['suck', 'move']",0.000000
49,com.brentpanther.bitcoinwidget,"['fetch', 'data', 'coingecko', 'kinda', 'buggy...",0.412500
50,com.brentpanther.bitcoinwidget,"['awesome', 'app', 'job', 'brilliantly', 'one'...",0.330000
51,com.brentpanther.bitcoinwidget,"['nice', 'app']",0.600000
52,com.brentpanther.bitcoinwidget,"['widget', 'hang', 'phone']",0.000000
53,com.brentpanther.bitcoinwidget,"['good', 'app', 'nice', 'download', 'problem']",0.650000
54,com.brentpanther.bitcoinwidget,"['work', 'great', 'love', 'stack', 'widget', '...",0.500000
55,com.brentpanther.bitcoinwidget,"['excelent', 'thank', 'soo', 'much']",0.200000
56,com.brentpanther.bitcoinwidget,"['one', 'best', 'ive', 'found']",1.000000
57,com.brentpanther.bitcoinwidget,"['thank', 'free', 'application', 'could', 'ple...",0.400000
58,com.brentpanther.bitcoinwidget,"['could', 'open', 'otherwisely']",0.000000
59,com.brentpanther.bitcoinwidget,['perfect'],1.000000
60,com.brentpanther.bitcoinwidget,"['widget', 'good', 'like', 'see', 'option', 's...",0.350000
61,com.brentpanther.bitcoinwidget,['working'],0.000000
62,com.brentpanther.bitcoinwidget,"['amazing', 'widged', 'simply', 'mean', 'light...",-0.022500
63,com.brentpanther.bitcoinwidget,['outstanding'],0.500000
64,com.brentpanther.bitcoinwidget,"['trouble', 'battery', 'saver', 'mine', 'calle...",0.075000
65,com.brentpanther.bitcoinwidget,"['needed', 'homescreen']",0.000000
66,com.brentpanther.bitcoinwidget,"['great', 'app', 'love', 'please', 'also', 'ad...",0.650000
67,com.brentpanther.bitcoinwidget,"['great', 'option', 'simple', 'use', 'clean', ...",0.460000
68,com.brentpanther.bitcoinwidget,"['say', 'love', 'log', 'something']",0.500000
69,com.brentpanther.bitcoinwidget,"['add', 'font', 'size']",0.000000
70,com.brentpanther.bitcoinwidget,"['simple', 'need']",0.000000
71,com.brentpanther.bitcoinwidget,"['great', 'app', 'good', 'simple', 'non', 'inv...",0.500000
72,com.brentpanther.bitcoinwidget,"['great', 'app']",0.800000
73,com.brentpanther.bitcoinwidget,['perfect'],1.000000
74,com.brentpanther.bitcoinwidget,"['put', 'three', 'widget', 'time']",0.000000
75,com.brentpanther.bitcoinwidget,"['tolong', 'update', 'data', 'dari', 'ajaib', ...",0.000000
76,com.brentpanther.bitcoinwidget,"['simple', 'work', 'nice', 'widget', 'love', '...",0.520000
77,com.brentpanther.bitcoinwidget,[],0.000000
78,com.brentpanther.bitcoinwidget,"['may', 'work', 'didnt', 'see', 'way', 'add', ...",0.000000
79,com.brentpanther.bitcoinwidget,"['please', 'set', 'one', 'two', 'candle', 'wid...",0.000000
80,com.brentpanther.bitcoinwidget,"['simple', 'work', 'look', 'great', 'pull', 'c...",0.500000
81,com.brentpanther.bitcoinwidget,"['nice', 'widget', 'need', 'percent', 'delta',...",0.300000
82,com.brentpanther.bitcoinwidget,"['work', 'great']",0.800000
83,com.brentpanther.bitcoinwidget,"['need', 'refresh', 'rate', 'live', 'five', 'm...",0.148182
84,com.brentpanther.bitcoinwidget,"['simply', 'supposed', 'provide', 'widget', 'd...",0.000000
85,com.brentpanther.bitcoinwidget,"['love', 'app', 'also', 'update', 'price', 'ra...",0.750000
86,com.brentpanther.bitcoinwidget,"['great', 'little', 'tool', 'thank']",0.306250
87,com.brentpanther.bitcoinwidget,"['actually', 'usefull']",0.000000
88,com.brentpanther.bitcoinwidget,"['everything', 'need', 'nonsense']",0.000000
89,com.brentpanther.bitcoinwidget,"['love', 'simple', 'work', 'perfectly', 'well'...",0.575000
90,com.brentpanther.bitcoinwidget,"['perfect', 'thank']",1.000000
91,com.brentpanther.bitcoinwidget,"['missing', 'feature', 'last', 'since', 'time'...",0.290000
92,com.brentpanther.bitcoinwidget,"['simple', 'use']",0.000000
93,com.brentpanther.bitcoinwidget,"['simple', 'yet', 'super', 'customizable', 'wi...",0.266667
94,com.brentpanther.bitcoinwidget,"['rubbish', 'worthless', 'never', 'updateswors...",-0.800000
95,com.brentpanther.bitcoinwidget,"['font', 'small', 'widget', 'broken']",-0.325000
96,com.brentpanther.bitcoinwidget,"['pity', 'option', 'change', 'currency']",-0.100000
97,com.brentpanther.bitcoinwidget,"['would', 'good', 'app', 'would', 'auto', 'upd...",0.700000
98,com.brentpanther.bitcoinwidget,"['app', 'potential', 'please', 'add', 'inx', '...",-0.035714
99,com.brentpanther.bitcoinwidget,"['give', 'five', 'star', 'plsr', 'added']",0.000000
100,com.brentpanther.bitcoinwidget,"['really', 'user', 'friendly', 'simple', 'use']",0.191667
101,com.brentpanther.bitcoinwidget,"['absolutely', 'bang', 'minimalist', 'widget',...",0.600000
102,com.brentpanther.bitcoinwidget,"['doesnt', 'work', 'anymore']",0.000000
103,com.brentpanther.bitcoinwidget,"['best', 'app', 'light', 'weight', 'absolutely...",0.600000
104,com.brentpanther.bitcoinwidget,['perfect'],1.000000
105,com.brentpanther.bitcoinwidget,"['brilliant', 'simple', 'took', 'set', 'effort...",0.400000
106,com.brentpanther.bitcoinwidget,"['simple', 'good', 'need', 'decimal', 'place',...",0.175000
107,com.brentpanther.bitcoinwidget,"['love', 'little', 'widget', 'whole', 'portfol...",0.216071
108,com.brentpanther.bitcoinwidget,"['please', 'add', 'unqt', 'token', 'widget', '...",0.000000
109,com.brentpanther.bitcoinwidget,"['exactly', 'want', 'one', 'x', 'one', 'widget...",0.425000
110,com.brentpanther.bitcoinwidget,"['thnx', 'much']",0.200000
111,com.brentpanther.bitcoinwidget,"['work', 'amazing', 'would', 'pay', 'pro', 've...",0.600000
112,com.brentpanther.bitcoinwidget,['good'],0.700000
113,com.brentpanther.bitcoinwidget,['good'],0.700000
114,com.brentpanther.bitcoinwidget,"['superb', 'apps']",1.000000
115,com.brentpanther.bitcoinwidget,"['work', 'sometimes', 'time', 'doesnt', 'add',...",0.068182
116,com.brentpanther.bitcoinwidget,"['easy', 'setup']",0.433333
117,com.brentpanther.bitcoinwidget,"['simple', 'functional']",0.000000
118,com.brentpanther.bitcoinwidget,['incorrect'],0.000000
119,com.brentpanther.bitcoinwidget,"['preferred', 'currency', 'bam', 'shown', 'wid...",-0.041667
120,com.brentpanther.bitcoinwidget,"['best', 'one', 'yet', 'could', 'better', 'sim...",0.139286
121,com.brentpanther.bitcoinwidget,"['perfect', 'app', 'exactly', 'say', 'tin']",0.625000
122,com.brentpanther.bitcoinwidget,"['top', 'notch']",0.500000
123,com.brentpanther.bitcoinwidget,"['thank', 'fixing', 'currency', 'issue', 'quic...",0.333333
124,com.brentpanther.bitcoinwidget,"['material', 'support', 'incredible']",0.900000
125,com.brentpanther.bitcoinwidget,"['great', 'app']",0.800000
126,com.brentpanther.bitcoinwidget,"['love', 'app', 'need', 'refresh', 'widget', '...",0.500000
127,com.brentpanther.bitcoinwidget,"['ive', 'annoyed', 'binance', 'widget', 'long'...",-0.037500
128,com.brentpanther.bitcoinwidget,"['great', 'widget', 'exactly', 'claim', 'devel...",0.461111
129,com.brentpanther.bitcoinwidget,"['refresh', 'interval', 'one', 'second', 'give...",0.000000
130,com.brentpanther.bitcoinwidget,['work'],0.000000
131,com.brentpanther.bitcoinwidget,"['great', 'work', 'half', 'time', 'though', 'w...",0.294444
132,com.brentpanther.bitcoinwidget,"['best', 'widget', 'reccomend', 'everybody']",1.000000
133,com.brentpanther.bitcoinwidget,"['absolutely', 'simple', 'clear']",0.050000
134,com.brentpanther.bitcoinwidget,"['perfectly', 'exactly', 'one', 'hundred', 'de...",0.150000
135,com.brentpanther.bitcoinwidget,"['easy', 'use', 'good', 'customization', 'opti...",0.395833
136,com.brentpanther.bitcoinwidget,"['wow', 'bulletproof', 'ever', 'decided', 'sta...",-0.350000
137,com.brentpanther.bitcoinwidget,"['nice', 'app']",0.600000
138,com.brentpanther.bitcoinwidget,"['please', 'include', 'option', 'open', 'coing...",0.333333
139,com.brentpanther.bitcoinwidget,"['best', 'widget', 'ive', 'found', 'far', 'sup...",0.266667
140,com.brentpanther.bitcoinwidget,"['app', 'worked', 'perfectly', 'year', 'size',...",0.276667
141,com.brentpanther.bitcoinwidget,"['love', 'little', 'thing', 'ad', 'trying', 'p...",0.174811
142,com.brentpanther.bitcoinwidget,"['used', 'work', 'perfectly', 'last', 'update'...",0.209722
143,com.brentpanther.bitcoinwidget,"['font', 'size', 'suddenly', 'became', 'small'...",-0.125000
144,com.brentpanther.bitcoinwidget,"['uninstalling', 'may', 'reinstall', 'future',...",0.000000
145,com.brentpanther.bitcoinwidget,['best'],1.000000
146,com.brentpanther.bitcoinwidget,"['amazing', 'app', 'amazing', 'service', 'deve...",0.600000
147,com.brentpanther.bitcoinwidget,"['ui', 'standpoint', 'new', 'update', 'screwed...",0.068182
148,com.brentpanther.bitcoinwidget,"['installed', 'phone', 'without', 'permission'...",0.000000
149,com.brentpanther.bitcoinwidget,"['finally', 'found', 'one', 'perfect', 'please...",0.500000
150,com.brentpanther.bitcoinwidget,['excelent'],0.000000
151,com.brentpanther.bitcoinwidget,"['work', 'well']",0.000000
152,com.brentpanther.bitcoinwidget,"['installation', 'gui', 'available', 'see', 'a...",0.400000
153,com.brentpanther.bitcoinwidget,"['ive', 'looking', 'app', 'like', 'age']",0.000000
154,com.brentpanther.bitcoinwidget,"['cannot', 'switch', 'currency', 'always', 'usd']",0.000000
155,com.brentpanther.bitcoinwidget,['perfect'],1.000000
156,com.brentpanther.bitcoinwidget,[],0.000000
157,com.brentpanther.bitcoinwidget,"['show', 'phone', 'downloaded']",0.000000
158,com.brentpanther.bitcoinwidget,"['loaded', 'app', 'twice', 'icon', 'wasnt', 'a...",0.500000
159,com.brentpanther.bitcoinwidget,['useless'],-0.500000
160,com.brentpanther.bitcoinwidget,"['looking', 'b', 'simple', 'widget']",0.000000
161,com.brentpanther.bitcoinwidget,"['excellent', 'application']",1.000000
162,com.brentpanther.bitcoinwidget,"['great', 'widget']",0.800000
163,com.brentpanther.bitcoinwidget,"['finally', 'app', 'personalise', 'specific', ...",0.260000
164,com.brentpanther.bitcoinwidget,"['installs', 'let', 'open', 'virus', 'scan', '...",0.000000
165,com.brentpanther.bitcoinwidget,"['stopped', 'working', 'today']",0.000000
166,com.brentpanther.bitcoinwidget,"['simple', 'clear', 'exactly', 'needed', 'woul...",0.087500
167,com.brentpanther.bitcoinwidget,"['many', 'search', 'finally', 'something', 'sh...",0.416667
168,com.brentpanther.bitcoinwidget,"['light', 'simple', 'good']",0.366667
169,com.brentpanther.bitcoinwidget,['good'],0.700000
170,com.brentpanther.bitcoinwidget,"['issue', 'widget', 'showing', 'spinner', 'dev...",0.633333
171,com.brentpanther.bitcoinwidget,"['four', 'star', 'requires', 'baterry', 'save'...",0.350000
172,com.brentpanther.bitcoinwidget,"['work', 'great', 'cant', 'find', 'way', 'edit...",0.400000
173,com.brentpanther.bitcoinwidget,"['say', 'simple', 'widget', 'track', 'price']",0.000000
174,com.brentpanther.bitcoinwidget,"['great', 'widget']",0.800000
175,com.brentpanther.bitcoinwidget,"['stopped', 'working', 'day', 'ago', 'galaxy',...",0.000000
176,com.brentpanther.bitcoinwidget,"['question', 'possible', 'see', 'list', 'coin']",0.000000
177,com.brentpanther.bitcoinwidget,"['tried', 'app', 'year', 'ago', 'inconsistent'...",0.250000
178,com.brentpanther.bitcoinwidget,['good'],0.700000
179,com.brentpanther.bitcoinwidget,"['best', 'widget']",1.000000
180,com.brentpanther.bitcoinwidget,"['widget', 'stop', 'working', 'reboot', 'gave'...",0.533333
181,com.brentpanther.bitcoinwidget,"['great', 'finally', 'widget', 'show', 'value'...",0.380000
182,com.brentpanther.bitcoinwidget,['awesome'],1.000000
183,com.brentpanther.bitcoinwidget,['good'],0.700000
184,com.brentpanther.bitcoinwidget,"['nice', 'simple', 'working', 'save', 'power']",0.300000
185,com.brentpanther.bitcoinwidget,"['simple', 'useful']",0.150000
186,com.brentpanther.bitcoinwidget,"['difficult', 'customize', 'setting', 'button']",-0.500000
187,com.brentpanther.bitcoinwidget,"['simple', 'concise', 'widget', 'exactly', 'lo...",0.116667
188,com.brentpanther.bitcoinwidget,['good'],0.700000
189,com.brentpanther.bitcoinwidget,"['wouldnt', 'work', 'android', 'downloaded', '...",0.000000
190,com.brentpanther.bitcoinwidget,"['bloatware', 'straight', 'point', 'customizab...",0.200000
191,com.brentpanther.bitcoinwidget,"['since', 'last', 'update', 'doesnt', 'work', ...",0.050000
192,com.brentpanther.bitcoinwidget,"['simplicity', 'ultimate', 'sophistication']",0.000000
193,com.brentpanther.bitcoinwidget,"['nice', 'one', 'option', 'would', 'grant', 'f...",0.600000
194,com.brentpanther.bitcoinwidget,"['easy', 'use', 'well', 'laid', 'good', 'work']",0.566667
195,com.brentpanther.bitcoinwidget,"['wanted', 'widget', 'show', 'price', 'bitcoin...",0.000000
196,com.brentpanther.bitcoinwidget,"['look', 'pretty', 'good', 'please', 'fix', 'p...",0.475000
197,com.brentpanther.bitcoinwidget,"['didnt', 'work']",0.000000
198,com.brentpanther.bitcoinwidget,"['straight', 'say']",0.200000
199,com.brentpanther.bitcoinwidget,"['great', 'app', 'say', 'thank', 'id', 'love',...",0.560000
200,com.brentpanther.bitcoinwidget,"['frequently', 'loading']",0.100000
201,com.brentpanther.bitcoinwidget,"['best', 'widget', 'found', 'existing', 'simpl...",0.500000
202,com.brentpanther.bitcoinwidget,"['doesnt', 'run', 'galaxy', 'fifty-one', 'five...",0.000000
203,com.brentpanther.bitcoinwidget,"['nope', 'work']",0.000000
204,com.brentpanther.bitcoinwidget,"['love', 'app', 'save', 'lot', 'time', 'obsess...",0.350000
205,com.brentpanther.bitcoinwidget,"['exactly', 'looking', 'thank']",0.250000
206,com.brentpanther.bitcoinwidget,"['doesnt', 'work', 'cant', 'open']",0.000000
207,com.brentpanther.bitcoinwidget,['good'],0.700000
208,com.brentpanther.bitcoinwidget,[],0.000000
209,com.brentpanther.bitcoinwidget,"['nowadays', 'refreshes', 'stop', 'refresh', '...",0.000000
210,com.brentpanther.bitcoinwidget,"['used', 'grear', 'nowadays', 'mostly', 'get',...",0.250000
211,com.brentpanther.bitcoinwidget,"['working', 'phone']",0.000000
212,com.brentpanther.bitcoinwidget,"['work', 'great', 'many', 'different', 'curren...",0.425000
213,com.brentpanther.bitcoinwidget,"['ok', 'good', 'sometimes', 'vanish', 'refresh...",0.284091
214,com.brentpanther.bitcoinwidget,[],0.000000
215,com.brentpanther.bitcoinwidget,"['simply', 'perfect']",1.000000
216,com.brentpanther.bitcoinwidget,"['amazing', 'app', 'important', 'coin', 'missi...",0.266667
217,com.brentpanther.bitcoinwidget,"['thanks', 'fixing', 'reboot', 'issue', 'widge...",0.500000
218,com.brentpanther.bitcoinwidget,"['simple', 'work', 'two', 'favourite', 'word',...",0.420000
219,com.brentpanther.bitcoinwidget,"['useful', 'lightweight', 'widget', 'thanks', ...",0.322222
220,com.brentpanther.bitcoinwidget,['ok'],0.500000
221,com.brentpanther.bitcoinwidget,"['stopped', 'working', 'phone', 'reboot', 'won...",0.000000
222,com.brentpanther.bitcoinwidget,"['simple', 'efficient', 'tool', 'display', 'cr...",0.000000
223,com.brentpanther.bitcoinwidget,"['useful', 'app']",0.300000
224,com.brentpanther.bitcoinwidget,"['five', 'star', 'oxt', 'added']",0.000000
225,com.brentpanther.bitcoinwidget,['nice'],0.600000
226,com.brentpanther.bitcoinwidget,"['bad', 'wery', 'baad']",-0.700000
227,com.brentpanther.bitcoinwidget,"['love', 'widget']",0.500000
228,com.brentpanther.bitcoinwidget,"['perpetually', 'load', 'restart', 'device']",-0.050000
229,com.brentpanther.bitcoinwidget,['thank'],0.000000
230,com.brentpanther.bitcoinwidget,"['could', 'add', 'robinhood', 'exchange', 'tha...",0.000000
231,com.brentpanther.bitcoinwidget,"['great', 'little', 'app']",0.306250
232,com.brentpanther.bitcoinwidget,[],0.000000
233,com.brentpanther.bitcoinwidget,"['great', 'app', 'work', 'well']",0.800000
234,com.brentpanther.bitcoinwidget,[],0.000000
235,com.brentpanther.bitcoinwidget,"['awesome', 'wish', 'listed', 'token']",1.000000
236,com.brentpanther.bitcoinwidget,"['decent', 'widget', 'bad', 'there', 'way', 's...",-0.266667
237,com.brentpanther.bitcoinwidget,"['greate', 'app', 'easy', 'use']",0.433333
238,com.brentpanther.bitcoinwidget,"['add', 'one', 'oops', 'five', 'two', 'thousan...",0.000000
239,com.brentpanther.bitcoinwidget,"['really', 'good', 'app']",0.700000
240,com.brentpanther.bitcoinwidget,"['back', 'old', 'behavior', 'working', 'update...",-0.033333
241,com.brentpanther.bitcoinwidget,"['bitcoin', 'move', 'fast', 'cant', 'wait', 'f...",0.200000

In [83]:
#!pip install vaderSentiment
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

data = pd.read_csv("Task3Input.csv")
analyzer = SentimentIntensityAnalyzer()

def sentiment_Vader(text):
    over_all_polarity = analyzer.polarity_scores(text)['compound']
    return over_all_polarity 

data['Polarity'] = data["Review_Text"].apply(lambda x: sentiment_Vader(x))

data.to_csv('Task3VaderOutput.csv', index = False)
                                             
data.head(1000)

,Package_Name,Review_Text,Polarity
0,com.brentpanther.bitcoinwidget,"['error', 'data', 'coin', 'gecko']",-0.4019
1,com.brentpanther.bitcoinwidget,"['simple', 'clean']",0.4019
2,com.brentpanther.bitcoinwidget,"['app', 'exactly', 'im', 'looking', 'especiall...",0.8720
3,com.brentpanther.bitcoinwidget,['good'],0.4404
4,com.brentpanther.bitcoinwidget,"['great', 'widget', 'show', 'currency', 'wallet']",0.6249
5,com.brentpanther.bitcoinwidget,"['best', 'bitcoin', 'widget']",0.6369
6,com.brentpanther.bitcoinwidget,"['simple', 'yet', 'brilliant', 'adjustment', '...",0.9488
7,com.brentpanther.bitcoinwidget,"['app', 'personally', 'easiest', 'crypto', 'ap...",0.7964
8,com.brentpanther.bitcoinwidget,"['like', 'exactly', 'described', 'simple', 'cr...",0.8739
9,com.brentpanther.bitcoinwidget,"['used', 'good', 'stopped', 'working', 'latest...",0.2500
10,com.brentpanther.bitcoinwidget,"['devs', 'reply', 'comment', 'already', 'lates...",0.3818
11,com.brentpanther.bitcoinwidget,"['work', 'awesome']",0.6249
12,com.brentpanther.bitcoinwidget,"['really', 'wanted', 'widget', 'home', 'screen...",0.0000
13,com.brentpanther.bitcoinwidget,"['solid', 'app', 'year', 'noticing', 'price', ...",-0.1531
14,com.brentpanther.bitcoinwidget,"['widget', 'working', 'correctly', 'dont', 'up...",0.0000
15,com.brentpanther.bitcoinwidget,['good'],0.4404
16,com.brentpanther.bitcoinwidget,"['ek', 'ek', 'ek', 'ek', 'bot', 'valid', 'revi...",0.0000
17,com.brentpanther.bitcoinwidget,"['real', 'trouble', 'updating', 'price', 'rece...",-0.4019
18,com.brentpanther.bitcoinwidget,"['use', 'every', 'day']",0.0000
19,com.brentpanther.bitcoinwidget,"['simple', 'sexy', 'job', 'pretty', 'well']",0.8271
20,com.brentpanther.bitcoinwidget,"['working', 'want', 'select', 'karlsonthe', 'a...",0.0772
21,com.brentpanther.bitcoinwidget,"['faster', 'refresh', 'everything', 'wanted']",0.0000
22,com.brentpanther.bitcoinwidget,['great'],0.6249
23,com.brentpanther.bitcoinwidget,"['new', 'update', 'longer', 'place', 'crypto',...",0.2023
24,com.brentpanther.bitcoinwidget,"['good', 'would', 'great', 'could', 'add', 'on...",0.7906
25,com.brentpanther.bitcoinwidget,"['work', 'update', 'price', 'almost', 'week']",0.0000
26,com.brentpanther.bitcoinwidget,"['seems', 'pretty', 'good', 'far', 'one', 'sug...",0.8126
27,com.brentpanther.bitcoinwidget,['nine'],0.0000
28,com.brentpanther.bitcoinwidget,"['far', 'best', 'looking', 'simplest', 'crypto...",0.6369
29,com.brentpanther.bitcoinwidget,['good'],0.4404
30,com.brentpanther.bitcoinwidget,"['app', 'freezez', 'sometimes', 'also', 'funct...",0.0000
31,com.brentpanther.bitcoinwidget,"['work', 'good', 'great', 'keep', 'eye', 'mark...",0.8207
32,com.brentpanther.bitcoinwidget,"['wanted', 'simply', 'stealth', 'update']",-0.0772
33,com.brentpanther.bitcoinwidget,"['lovely', 'point', 'exactly', 'needed']",0.5859
34,com.brentpanther.bitcoinwidget,"['say', 'version', 'simple', 'crypto', 'widget...",0.9766
35,com.brentpanther.bitcoinwidget,['good'],0.4404
36,com.brentpanther.bitcoinwidget,"['great', 'app', 'simple', 'useful']",0.7906
37,com.brentpanther.bitcoinwidget,"['top', 'top']",0.3818
38,com.brentpanther.bitcoinwidget,"['hello', 'im', 'deaf', 'please']",0.3182
39,com.brentpanther.bitcoinwidget,"['simple', 'pretty', 'open', 'source']",0.4939
40,com.brentpanther.bitcoinwidget,['great'],0.6249
41,com.brentpanther.bitcoinwidget,"['seems', 'incompatible', 'android', 'six', 'h...",0.7906
42,com.brentpanther.bitcoinwidget,"['everything', 'want', 'perfect']",0.6124
43,com.brentpanther.bitcoinwidget,"['love', 'made', 'little', 'le', 'simple', 'co...",0.9186
44,com.brentpanther.bitcoinwidget,"['need', 'sometimes', 'price', 'dont', 'update...",0.6249
45,com.brentpanther.bitcoinwidget,"['convenient', 'accurate', 'stopped', 'working']",-0.2263
46,com.brentpanther.bitcoinwidget,"['great', 'app', 'created', 'widget', 'showing...",0.8225
47,com.brentpanther.bitcoinwidget,"['great', 'app', 'wish', 'add', 'couns']",0.7783
48,com.brentpanther.bitcoinwidget,"['suck', 'move']",-0.4404
49,com.brentpanther.bitcoinwidget,"['fetch', 'data', 'coingecko', 'kinda', 'buggy...",0.8750
50,com.brentpanther.bitcoinwidget,"['awesome', 'app', 'job', 'brilliantly', 'one'...",0.8885
51,com.brentpanther.bitcoinwidget,"['nice', 'app']",0.4215
52,com.brentpanther.bitcoinwidget,"['widget', 'hang', 'phone']",0.0000
53,com.brentpanther.bitcoinwidget,"['good', 'app', 'nice', 'download', 'problem']",0.4588
54,com.brentpanther.bitcoinwidget,"['work', 'great', 'love', 'stack', 'widget', '...",0.9325
55,com.brentpanther.bitcoinwidget,"['excelent', 'thank', 'soo', 'much']",0.3612
56,com.brentpanther.bitcoinwidget,"['one', 'best', 'ive', 'found']",0.6369
57,com.brentpanther.bitcoinwidget,"['thank', 'free', 'application', 'could', 'ple...",0.8807
58,com.brentpanther.bitcoinwidget,"['could', 'open', 'otherwisely']",0.0000
59,com.brentpanther.bitcoinwidget,['perfect'],0.5719
60,com.brentpanther.bitcoinwidget,"['widget', 'good', 'like', 'see', 'option', 's...",0.7717
61,com.brentpanther.bitcoinwidget,['working'],0.0000
62,com.brentpanther.bitcoinwidget,"['amazing', 'widged', 'simply', 'mean', 'light...",0.8384
63,com.brentpanther.bitcoinwidget,['outstanding'],0.6124
64,com.brentpanther.bitcoinwidget,"['trouble', 'battery', 'saver', 'mine', 'calle...",-0.4019
65,com.brentpanther.bitcoinwidget,"['needed', 'homescreen']",0.0000
66,com.brentpanther.bitcoinwidget,"['great', 'app', 'love', 'please', 'also', 'ad...",0.9201
67,com.brentpanther.bitcoinwidget,"['great', 'option', 'simple', 'use', 'clean', ...",0.9371
68,com.brentpanther.bitcoinwidget,"['say', 'love', 'log', 'something']",0.6369
69,com.brentpanther.bitcoinwidget,"['add', 'font', 'size']",0.0000
70,com.brentpanther.bitcoinwidget,"['simple', 'need']",0.0000
71,com.brentpanther.bitcoinwidget,"['great', 'app', 'good', 'simple', 'non', 'inv...",0.7906
72,com.brentpanther.bitcoinwidget,"['great', 'app']",0.6249
73,com.brentpanther.bitcoinwidget,['perfect'],0.5719
74,com.brentpanther.bitcoinwidget,"['put', 'three', 'widget', 'time']",0.0000
75,com.brentpanther.bitcoinwidget,"['tolong', 'update', 'data', 'dari', 'ajaib', ...",0.0000
76,com.brentpanther.bitcoinwidget,"['simple', 'work', 'nice', 'widget', 'love', '...",0.9100
77,com.brentpanther.bitcoinwidget,[],0.0000
78,com.brentpanther.bitcoinwidget,"['may', 'work', 'didnt', 'see', 'way', 'add', ...",0.0000
79,com.brentpanther.bitcoinwidget,"['please', 'set', 'one', 'two', 'candle', 'wid...",0.3182
80,com.brentpanther.bitcoinwidget,"['simple', 'work', 'look', 'great', 'pull', 'c...",0.9638
81,com.brentpanther.bitcoinwidget,"['nice', 'widget', 'need', 'percent', 'delta',...",0.4215
82,com.brentpanther.bitcoinwidget,"['work', 'great']",0.6249
83,com.brentpanther.bitcoinwidget,"['need', 'refresh', 'rate', 'live', 'five', 'm...",0.0000
84,com.brentpanther.bitcoinwidget,"['simply', 'supposed', 'provide', 'widget', 'd...",0.0000
85,com.brentpanther.bitcoinwidget,"['love', 'app', 'also', 'update', 'price', 'ra...",0.8074
86,com.brentpanther.bitcoinwidget,"['great', 'little', 'tool', 'thank']",0.7447
87,com.brentpanther.bitcoinwidget,"['actually', 'usefull']",0.0000
88,com.brentpanther.bitcoinwidget,"['everything', 'need', 'nonsense']",-0.4019
89,com.brentpanther.bitcoinwidget,"['love', 'simple', 'work', 'perfectly', 'well'...",0.9393
90,com.brentpanther.bitcoinwidget,"['perfect', 'thank']",0.7351
91,com.brentpanther.bitcoinwidget,"['missing', 'feature', 'last', 'since', 'time'...",0.7783
92,com.brentpanther.bitcoinwidget,"['simple', 'use']",0.0000
93,com.brentpanther.bitcoinwidget,"['simple', 'yet', 'super', 'customizable', 'wi...",0.9501
94,com.brentpanther.bitcoinwidget,"['rubbish', 'worthless', 'never', 'updateswors...",-0.4404
95,com.brentpanther.bitcoinwidget,"['font', 'small', 'widget', 'broken']",-0.4767
96,com.brentpanther.bitcoinwidget,"['pity', 'option', 'change', 'currency']",-0.2960
97,com.brentpanther.bitcoinwidget,"['would', 'good', 'app', 'would', 'auto', 'upd...",0.4404
98,com.brentpanther.bitcoinwidget,"['app', 'potential', 'please', 'add', 'inx', '...",0.4767
99,com.brentpanther.bitcoinwidget,"['give', 'five', 'star', 'plsr', 'added']",0.0000
100,com.brentpanther.bitcoinwidget,"['really', 'user', 'friendly', 'simple', 'use']",0.5390
101,com.brentpanther.bitcoinwidget,"['absolutely', 'bang', 'minimalist', 'widget',...",0.8481
102,com.brentpanther.bitcoinwidget,"['doesnt', 'work', 'anymore']",0.0000
103,com.brentpanther.bitcoinwidget,"['best', 'app', 'light', 'weight', 'absolutely...",0.6369
104,com.brentpanther.bitcoinwidget,['perfect'],0.5719
105,com.brentpanther.bitcoinwidget,"['brilliant', 'simple', 'took', 'set', 'effort...",0.7783
106,com.brentpanther.bitcoinwidget,"['simple', 'good', 'need', 'decimal', 'place',...",0.4404
107,com.brentpanther.bitcoinwidget,"['love', 'little', 'widget', 'whole', 'portfol...",0.9432
108,com.brentpanther.bitcoinwidget,"['please', 'add', 'unqt', 'token', 'widget', '...",0.3182
109,com.brentpanther.bitcoinwidget,"['exactly', 'want', 'one', 'x', 'one', 'widget...",0.8316
110,com.brentpanther.bitcoinwidget,"['thnx', 'much']",0.0000
111,com.brentpanther.bitcoinwidget,"['work', 'amazing', 'would', 'pay', 'pro', 've...",0.5267
112,com.brentpanther.bitcoinwidget,['good'],0.4404
113,com.brentpanther.bitcoinwidget,['good'],0.4404
114,com.brentpanther.bitcoinwidget,"['superb', 'apps']",0.6249
115,com.brentpanther.bitcoinwidget,"['work', 'sometimes', 'time', 'doesnt', 'add',...",0.0000
116,com.brentpanther.bitcoinwidget,"['easy', 'setup']",0.4404
117,com.brentpanther.bitcoinwidget,"['simple', 'functional']",0.0000
118,com.brentpanther.bitcoinwidget,['incorrect'],0.0000
119,com.brentpanther.bitcoinwidget,"['preferred', 'currency', 'bam', 'shown', 'wid...",0.3400
120,com.brentpanther.bitcoinwidget,"['best', 'one', 'yet', 'could', 'better', 'sim...",0.7269
121,com.brentpanther.bitcoinwidget,"['perfect', 'app', 'exactly', 'say', 'tin']",0.5719
122,com.brentpanther.bitcoinwidget,"['top', 'notch']",0.2023
123,com.brentpanther.bitcoinwidget,"['thank', 'fixing', 'currency', 'issue', 'quic...",0.3612
124,com.brentpanther.bitcoinwidget,"['material', 'support', 'incredible']",0.4019
125,com.brentpanther.bitcoinwidget,"['great', 'app']",0.6249
126,com.brentpanther.bitcoinwidget,"['love', 'app', 'need', 'refresh', 'widget', '...",0.7964
127,com.brentpanther.bitcoinwidget,"['ive', 'annoyed', 'binance', 'widget', 'long'...",0.4215
128,com.brentpanther.bitcoinwidget,"['great', 'widget', 'exactly', 'claim', 'devel...",0.6249
129,com.brentpanther.bitcoinwidget,"['refresh', 'interval', 'one', 'second', 'give...",0.0000
130,com.brentpanther.bitcoinwidget,['work'],0.0000
131,com.brentpanther.bitcoinwidget,"['great', 'work', 'half', 'time', 'though', 'w...",0.6249
132,com.brentpanther.bitcoinwidget,"['best', 'widget', 'reccomend', 'everybody']",0.6369
133,com.brentpanther.bitcoinwidget,"['absolutely', 'simple', 'clear']",0.4364
134,com.brentpanther.bitcoinwidget,"['perfectly', 'exactly', 'one', 'hundred', 'de...",0.7269
135,com.brentpanther.bitcoinwidget,"['easy', 'use', 'good', 'customization', 'opti...",0.7184
136,com.brentpanther.bitcoinwidget,"['wow', 'bulletproof', 'ever', 'decided', 'sta...",0.4191
137,com.brentpanther.bitcoinwidget,"['nice', 'app']",0.4215
138,com.brentpanther.bitcoinwidget,"['please', 'include', 'option', 'open', 'coing...",0.8519
139,com.brentpanther.bitcoinwidget,"['best', 'widget', 'ive', 'found', 'far', 'sup...",0.8807
140,com.brentpanther.bitcoinwidget,"['app', 'worked', 'perfectly', 'year', 'size',...",0.8442
141,com.brentpanther.bitcoinwidget,"['love', 'little', 'thing', 'ad', 'trying', 'p...",0.7906
142,com.brentpanther.bitcoinwidget,"['used', 'work', 'perfectly', 'last', 'update'...",0.9260
143,com.brentpanther.bitcoinwidget,"['font', 'size', 'suddenly', 'became', 'small'...",0.5859
144,com.brentpanther.bitcoinwidget,"['uninstalling', 'may', 'reinstall', 'future',...",0.0000
145,com.brentpanther.bitcoinwidget,['best'],0.6369
146,com.brentpanther.bitcoinwidget,"['amazing', 'app', 'amazing', 'service', 'deve...",0.8225
147,com.brentpanther.bitcoinwidget,"['ui', 'standpoint', 'new', 'update', 'screwed...",-0.4939
148,com.brentpanther.bitcoinwidget,"['installed', 'phone', 'without', 'permission'...",-0.2755
149,com.brentpanther.bitcoinwidget,"['finally', 'found', 'one', 'perfect', 'please...",0.8176
150,com.brentpanther.bitcoinwidget,['excelent'],0.0000
151,com.brentpanther.bitcoinwidget,"['work', 'well']",0.2732
152,com.brentpanther.bitcoinwidget,"['installation', 'gui', 'available', 'see', 'a...",0.0000
153,com.brentpanther.bitcoinwidget,"['ive', 'looking', 'app', 'like', 'age']",0.3612
154,com.brentpanther.bitcoinwidget,"['cannot', 'switch', 'currency', 'always', 'usd']",0.0000
155,com.brentpanther.bitcoinwidget,['perfect'],0.5719
156,com.brentpanther.bitcoinwidget,[],0.0000
157,com.brentpanther.bitcoinwidget,"['show', 'phone', 'downloaded']",0.0000
158,com.brentpanther.bitcoinwidget,"['loaded', 'app', 'twice', 'icon', 'wasnt', 'a...",0.0000
159,com.brentpanther.bitcoinwidget,['useless'],-0.4215
160,com.brentpanther.bitcoinwidget,"['looking', 'b', 'simple', 'widget']",0.0000
161,com.brentpanther.bitcoinwidget,"['excellent', 'application']",0.5719
162,com.brentpanther.bitcoinwidget,"['great', 'widget']",0.6249
163,com.brentpanther.bitcoinwidget,"['finally', 'app', 'personalise', 'specific', ...",0.8625
164,com.brentpanther.bitcoinwidget,"['installs', 'let', 'open', 'virus', 'scan', '...",0.0000
165,com.brentpanther.bitcoinwidget,"['stopped', 'working', 'today']",-0.2263
166,com.brentpanther.bitcoinwidget,"['simple', 'clear', 'exactly', 'needed', 'woul...",0.6249
167,com.brentpanther.bitcoinwidget,"['many', 'search', 'finally', 'something', 'sh...",0.7506
168,com.brentpanther.bitcoinwidget,"['light', 'simple', 'good']",0.4404
169,com.brentpanther.bitcoinwidget,['good'],0.4404
170,com.brentpanther.bitcoinwidget,"['issue', 'widget', 'showing', 'spinner', 'dev...",0.7650
171,com.brentpanther.bitcoinwidget,"['four', 'star', 'requires', 'baterry', 'save'...",0.8271
172,com.brentpanther.bitcoinwidget,"['work', 'great', 'cant', 'find', 'way', 'edit...",0.6249
173,com.brentpanther.bitcoinwidget,"['say', 'simple', 'widget', 'track', 'price']",0.0000
174,com.brentpanther.bitcoinwidget,"['great', 'widget']",0.6249
175,com.brentpanther.bitcoinwidget,"['stopped', 'working', 'day', 'ago', 'galaxy',...",-0.2263
176,com.brentpanther.bitcoinwidget,"['question', 'possible', 'see', 'list', 'coin']",0.0000
177,com.brentpanther.bitcoinwidget,"['tried', 'app', 'year', 'ago', 'inconsistent'...",0.7579
178,com.brentpanther.bitcoinwidget,['good'],0.4404
179,com.brentpanther.bitcoinwidget,"['best', 'widget']",0.6369
180,com.brentpanther.bitcoinwidget,"['widget', 'stop', 'working', 'reboot', 'gave'...",0.8468
181,com.brentpanther.bitcoinwidget,"['great', 'finally', 'widget', 'show', 'value'...",0.9001
182,com.brentpanther.bitcoinwidget,['awesome'],0.6249
183,com.brentpanther.bitcoinwidget,['good'],0.4404
184,com.brentpanther.bitcoinwidget,"['nice', 'simple', 'working', 'save', 'power']",0.7184
185,com.brentpanther.bitcoinwidget,"['simple', 'useful']",0.4404
186,com.brentpanther.bitcoinwidget,"['difficult', 'customize', 'setting', 'button']",-0.3612
187,com.brentpanther.bitcoinwidget,"['simple', 'concise', 'widget', 'exactly', 'lo...",0.0000
188,com.brentpanther.bitcoinwidget,['good'],0.4404
189,com.brentpanther.bitcoinwidget,"['wouldnt', 'work', 'android', 'downloaded', '...",0.0000
190,com.brentpanther.bitcoinwidget,"['bloatware', 'straight', 'point', 'customizab...",0.2263
191,com.brentpanther.bitcoinwidget,"['since', 'last', 'update', 'doesnt', 'work', ...",0.0000
192,com.brentpanther.bitcoinwidget,"['simplicity', 'ultimate', 'sophistication']",0.0000
193,com.brentpanther.bitcoinwidget,"['nice', 'one', 'option', 'would', 'grant', 'f...",0.6486
194,com.brentpanther.bitcoinwidget,"['easy', 'use', 'well', 'laid', 'good', 'work']",0.7845
195,com.brentpanther.bitcoinwidget,"['wanted', 'widget', 'show', 'price', 'bitcoin...",0.5423
196,com.brentpanther.bitcoinwidget,"['look', 'pretty', 'good', 'please', 'fix', 'p...",0.8126
197,com.brentpanther.bitcoinwidget,"['didnt', 'work']",0.0000
198,com.brentpanther.bitcoinwidget,"['straight', 'say']",0.2263
199,com.brentpanther.bitcoinwidget,"['great', 'app', 'say', 'thank', 'id', 'love',...",0.9648
200,com.brentpanther.bitcoinwidget,"['frequently', 'loading']",0.0000
201,com.brentpanther.bitcoinwidget,"['best', 'widget', 'found', 'existing', 'simpl...",0.6369
202,com.brentpanther.bitcoinwidget,"['doesnt', 'run', 'galaxy', 'fifty-one', 'five...",0.0000
203,com.brentpanther.bitcoinwidget,"['nope', 'work']",0.0000
204,com.brentpanther.bitcoinwidget,"['love', 'app', 'save', 'lot', 'time', 'obsess...",0.8555
205,com.brentpanther.bitcoinwidget,"['exactly', 'looking', 'thank']",0.3612
206,com.brentpanther.bitcoinwidget,"['doesnt', 'work', 'cant', 'open']",0.0000
207,com.brentpanther.bitcoinwidget,['good'],0.4404
208,com.brentpanther.bitcoinwidget,[],0.0000
209,com.brentpanther.bitcoinwidget,"['nowadays', 'refreshes', 'stop', 'refresh', '...",-0.2960
210,com.brentpanther.bitcoinwidget,"['used', 'grear', 'nowadays', 'mostly', 'get',...",-0.0191
211,com.brentpanther.bitcoinwidget,"['working', 'phone']",0.0000
212,com.brentpanther.bitcoinwidget,"['work', 'great', 'many', 'different', 'curren...",0.6249
213,com.brentpanther.bitcoinwidget,"['ok', 'good', 'sometimes', 'vanish', 'refresh...",0.4404
214,com.brentpanther.bitcoinwidget,[],0.0000
215,com.brentpanther.bitcoinwidget,"['simply', 'perfect']",0.5719
216,com.brentpanther.bitcoinwidget,"['amazing', 'app', 'important', 'coin', 'missi...",0.7096
217,com.brentpanther.bitcoinwidget,"['thanks', 'fixing', 'reboot', 'issue', 'widge...",0.7906
218,com.brentpanther.bitcoinwidget,"['simple', 'work', 'two', 'favourite', 'word',...",0.9169
219,com.brentpanther.bitcoinwidget,"['useful', 'lightweight', 'widget', 'thanks', ...",0.7783
220,com.brentpanther.bitcoinwidget,['ok'],0.0000
221,com.brentpanther.bitcoinwidget,"['stopped', 'working', 'phone', 'reboot', 'won...",-0.2263
222,com.brentpanther.bitcoinwidget,"['simple', 'efficient', 'tool', 'display', 'cr...",0.4215
223,com.brentpanther.bitcoinwidget,"['useful', 'app']",0.4404
224,com.brentpanther.bitcoinwidget,"['five', 'star', 'oxt', 'added']",0.0000
225,com.brentpanther.bitcoinwidget,['nice'],0.4215
226,com.brentpanther.bitcoinwidget,"['bad', 'wery', 'baad']",-0.5423
227,com.brentpanther.bitcoinwidget,"['love', 'widget']",0.6369
228,com.brentpanther.bitcoinwidget,"['perpetually', 'load', 'restart', 'device']",0.0000
229,com.brentpanther.bitcoinwidget,['thank'],0.3612
230,com.brentpanther.bitcoinwidget,"['could', 'add', 'robinhood', 'exchange', 'tha...",0.3612
231,com.brentpanther.bitcoinwidget,"['great', 'little', 'app']",0.6249
232,com.brentpanther.bitcoinwidget,[],0.0000
233,com.brentpanther.bitcoinwidget,"['great', 'app', 'work', 'well']",0.7351
234,com.brentpanther.bitcoinwidget,[],0.0000
235,com.brentpanther.bitcoinwidget,"['awesome', 'wish', 'listed', 'token']",0.7783
236,com.brentpanther.bitcoinwidget,"['decent', 'widget', 'bad', 'there', 'way', 's...",-0.5423
237,com.brentpanther.bitcoinwidget,"['greate', 'app', 'easy', 'use']",0.4404
238,com.brentpanther.bitcoinwidget,"['add', 'one', 'oops', 'five', 'two', 'thousan...",0.0000
239,com.brentpanther.bitcoinwidget,"['really', 'good', 'app']",0.4927
240,com.brentpanther.bitcoinwidget,"['back', 'old', 'behavior', 'working', 'update...",0.7003
241,com.brentpanther.bitcoinwidget,"['bitcoin', 'move', 'fast', 'cant', 'wait', 'f...",0.0000
242,com.brentpanther.bitcoinwidget,"['used', 'app', 'several', 'year', 'similar', ...",0.9781
243,com.brentpanther.bitcoinwidget,"['simple', 'set', 'read', 'exactly', 'looking']",0.0000
244,com.brentpanther.bitcoinwidget,"['deberan', 'agregar', 'm', 'criptomonedas', '...",0.0000
245,com.brentpanther.bitcoinwidget,['broke'],-0.4215
246,com.brentpanther.bitcoinwidget,"['good', 'app']",0.4404
247,com.brentpanther.bitcoinwidget,['alihelma'],0.0000

III. The first difference I noticed with the sentiment analysis was how textblob only outputs a single value that represents the overall polarity of the preprocessed review text, where as the vader sentiment analysis outputs four different values allowing us to see the amount of negative, neutral, positive, and compound polarity calculated during the sentiment analysis. I also noticed a difference in how they rate each review, for example the first review getting a 0.0 (neutral) where as vader gave it a compound of value of -0.4019 (negative). I believe this difference comes from how either calculates the polarity values, for example in the first review, vader calculated a overall negative polarity rating, however it also calculated a neutral polarity rating of 0.526. Textblob calculated a polarity of 0.0 meaning neutral, this could be from it calculating a majority of the review's sentiment as neutral, just like vader did, but instead deeming the overall sentiment of the review as neutral or 0.0. From comparing the actual reviews ratings and the sentiment analysis performed by both textblob and vader, I noticed that  on average, vader's sentiment analysis is closer to the real review ratings, where as textblob tends to be a little less accurate on average. However both sentiment analysis methods get the polarity incorrect at times. For example, both vader and textblob inaccurately represented the review on the fourteenth row, with vader giving it a compound polarity of -0.1531 and textblob giving it a rating of 0. The actual review however was given a five star rating, but the reviewer then wrote a small issue he was noticing with the app itself, making textblob and vader both think the review was either slightly on the negative side or neutral, as opposed to its actual perfect rating.

In [119]:
from tabulate import tabulate

mydata = [["['error', 'data', 'coin', 'gecko']", "0.000000", "-0.8"],
          ["['simple', 'clean']", "0.183333", "0.9"], 
          ["['app', 'exactly', 'im', 'looking', 'especially'...]", "0.307143", "0.3"],
          ["['good']", "0.700000", "0.9"],
          ["['great', 'widget', 'show', 'currency', 'wallet']", "0.800000", "0.8"],
          ["['best', 'bitcoin', 'widget']", "1.000000", "0.7"],
          ["['simple', 'yet', 'brilliant', 'adjustment'...] ", "0.392045", "0.9"],
          ["['app', 'personally', 'easiest', 'crypto', 'app'...]", "0.358333", "0.8"],
          ["['like', 'exactly', 'described', 'simple',...]", "0.177273", "0.9"],
          ["['used', 'good', 'stopped', 'working', 'latest',...]", "0.600000", "-0.7"],
          ["['devs', 'reply', 'comment', 'already', 'latest',...]", "0.179167", "-0.8"],
          ["['work', 'awesome']", "1.000000", "0.9"],
          ["['really', 'wanted', 'widget', 'home', 'screen',...]", "0.125000", "-0.6"],
          ["['solid', 'app', 'year', 'noticing', 'price',...]", "0.000000", "0.2"],
          ["['widget', 'working', 'correctly', 'dont',...]", "0.000000", "-0.8"]]
              

head = ["Review", "Textblob Sentiment", "ChatGPT Sentiment"]

print(tabulate(mydata, headers=head, tablefmt="grid"))

+-------------------------------------------------------+----------------------+---------------------+
| Review                                                |   Textblob Sentiment |   ChatGPT Sentiment |
+=======================================================+======================+=====================+
| ['error', 'data', 'coin', 'gecko']                    |             0        |                -0.8 |
+-------------------------------------------------------+----------------------+---------------------+
| ['simple', 'clean']                                   |             0.183333 |                 0.9 |
+-------------------------------------------------------+----------------------+---------------------+
| ['app', 'exactly', 'im', 'looking', 'especially'...]  |             0.307143 |                 0.3 |
+-------------------------------------------------------+----------------------+---------------------+
| ['good']                                              |             0.7      |                 0.9 |
+-------------------------------------------------------+----------------------+---------------------+
| ['great', 'widget', 'show', 'currency', 'wallet']     |             0.8      |                 0.8 |
+-------------------------------------------------------+----------------------+---------------------+
| ['best', 'bitcoin', 'widget']                         |             1        |                 0.7 |
+-------------------------------------------------------+----------------------+---------------------+
| ['simple', 'yet', 'brilliant', 'adjustment'...]       |             0.392045 |                 0.9 |
+-------------------------------------------------------+----------------------+---------------------+
| ['app', 'personally', 'easiest', 'crypto', 'app'...]  |             0.358333 |                 0.8 |
+-------------------------------------------------------+----------------------+---------------------+
| ['like', 'exactly', 'described', 'simple',...]        |             0.177273 |                 0.9 |
+-------------------------------------------------------+----------------------+---------------------+
| ['used', 'good', 'stopped', 'working', 'latest',...]  |             0.6      |                -0.7 |
+-------------------------------------------------------+----------------------+---------------------+
| ['devs', 'reply', 'comment', 'already', 'latest',...] |             0.179167 |                -0.8 |
+-------------------------------------------------------+----------------------+---------------------+
| ['work', 'awesome']                                   |             1        |                 0.9 |
+-------------------------------------------------------+----------------------+---------------------+
| ['really', 'wanted', 'widget', 'home', 'screen',...]  |             0.125    |                -0.6 |
+-------------------------------------------------------+----------------------+---------------------+
| ['solid', 'app', 'year', 'noticing', 'price',...]     |             0        |                 0.2 |
+-------------------------------------------------------+----------------------+---------------------+
| ['widget', 'working', 'correctly', 'dont',...]        |             0        |                -0.8 |
+-------------------------------------------------------+----------------------+---------------------+

In [120]:
mydata = [["['error', 'data', 'coin', 'gecko']", "-0.4019", "-0.8"],
          ["['simple', 'clean']", "0.4019", "0.9"], 
          ["['app', 'exactly', 'im', 'looking', 'especially'...]", "0.8720", "0.3"],
          ["['good']", "0.4404", "0.9"],
          ["['great', 'widget', 'show', 'currency', 'wallet']", "0.6249", "0.8"],
          ["['best', 'bitcoin', 'widget']", "0.6369", "0.7"],
          ["['simple', 'yet', 'brilliant', 'adjustment'...] ", "0.9488", "0.9"],
          ["['app', 'personally', 'easiest', 'crypto', 'app'...]", "0.7964", "0.8"],
          ["['like', 'exactly', 'described', 'simple',...]", "0.8739", "0.9"],
          ["['used', 'good', 'stopped', 'working', 'latest',...]", "0.2500", "-0.7"],
          ["['devs', 'reply', 'comment', 'already', 'latest',...]", "0.3818", "-0.8"],
          ["['work', 'awesome']", "0.6249", "0.9"],
          ["['really', 'wanted', 'widget', 'home', 'screen',...]", "0.0000", "-0.6"],
          ["['solid', 'app', 'year', 'noticing', 'price',...]", "-0.1531", "0.2"],
          ["['widget', 'working', 'correctly', 'dont',...]", "0.0000", "-0.8"]]
              

head = ["Review", "Vader Sentiment", "ChatGPT Sentiment"]

print(tabulate(mydata, headers=head, tablefmt="grid"))

+-------------------------------------------------------+-------------------+---------------------+
| Review                                                |   Vader Sentiment |   ChatGPT Sentiment |
+=======================================================+===================+=====================+
| ['error', 'data', 'coin', 'gecko']                    |           -0.4019 |                -0.8 |
+-------------------------------------------------------+-------------------+---------------------+
| ['simple', 'clean']                                   |            0.4019 |                 0.9 |
+-------------------------------------------------------+-------------------+---------------------+
| ['app', 'exactly', 'im', 'looking', 'especially'...]  |            0.872  |                 0.3 |
+-------------------------------------------------------+-------------------+---------------------+
| ['good']                                              |            0.4404 |                 0.9 |
+-------------------------------------------------------+-------------------+---------------------+
| ['great', 'widget', 'show', 'currency', 'wallet']     |            0.6249 |                 0.8 |
+-------------------------------------------------------+-------------------+---------------------+
| ['best', 'bitcoin', 'widget']                         |            0.6369 |                 0.7 |
+-------------------------------------------------------+-------------------+---------------------+
| ['simple', 'yet', 'brilliant', 'adjustment'...]       |            0.9488 |                 0.9 |
+-------------------------------------------------------+-------------------+---------------------+
| ['app', 'personally', 'easiest', 'crypto', 'app'...]  |            0.7964 |                 0.8 |
+-------------------------------------------------------+-------------------+---------------------+
| ['like', 'exactly', 'described', 'simple',...]        |            0.8739 |                 0.9 |
+-------------------------------------------------------+-------------------+---------------------+
| ['used', 'good', 'stopped', 'working', 'latest',...]  |            0.25   |                -0.7 |
+-------------------------------------------------------+-------------------+---------------------+
| ['devs', 'reply', 'comment', 'already', 'latest',...] |            0.3818 |                -0.8 |
+-------------------------------------------------------+-------------------+---------------------+
| ['work', 'awesome']                                   |            0.6249 |                 0.9 |
+-------------------------------------------------------+-------------------+---------------------+
| ['really', 'wanted', 'widget', 'home', 'screen',...]  |            0      |                -0.6 |
+-------------------------------------------------------+-------------------+---------------------+
| ['solid', 'app', 'year', 'noticing', 'price',...]     |           -0.1531 |                 0.2 |
+-------------------------------------------------------+-------------------+---------------------+
| ['widget', 'working', 'correctly', 'dont',...]        |            0      |                -0.8 |
+-------------------------------------------------------+-------------------+---------------------+

IV. a) The prompt I used for ChatGPT was: Perform sentiment analysis on these 15 reviews and represent sentiment as a float value between -1 and 1, but perform the sentiment analysis yourself, do not use code of any kind: "Error again data from coin gecko", "simple and clean", "This app is exactly what I'm looking for especially when I see meme coins on here to be added on my phone. The only thing I wish you could do is selecting a widget of your favorite coin and it would show you the price history chart either by the day or the minute, etc in real time prices similar to tradingview. Other than this, its good. Not sure if this will happen in my case but what if it doesn't have a coin you are looking for? There are a lot of choices out there. Just my thoughts. 😎 🤑", "Good", "Great widget. Shows currency and your wallet", "Best Bitcoin widget out there.",  
"So simple yet so brilliant. The adjustments you can make to the look of the widgets are perfect, and the fact you can edit "live" widgets without having to delete them then reinstate them is a huge bonus. Sometimes apps are made so complicated they become unusable, but this one is just perfect for what I wanted. Thanks to the developer!", "This app personally has been the easiest crypto app to navigate I've ever used I'm excited to keep using it. Keep up the good work.", "I like this. Does exactly as described! It's a simple crypto widget, (you can actually have multiple widgets) they look good and can be customised. Very simple interface, no crashes and it doesn't ask for your API keys to display your wallet totals. Would it be possible to include a widget that displays the sum total of the widgets displayed? Thanks for a great app. Also, put a donate link in the settings!
Used to be good, then it stopped working after the latest update
Re devs reply comment: I was already on latest version. Looks good, but there are serious issues with price updates. MORE PRICE FEED OPTIONS REQUIRED OTHER THAN COINGECKO. Many tokens which are listed on Kucoin (for example) only have a Coingecko price feed option (e.g. ASTAR has no kucoin price feed option) and the Coingecko feed hardly ever updates properly. Of the 12 or so tokens I have as widgets, the majority do not update at any given time. Even tapping to manually update does not work.", "Works awesome!!!!", "really wanted a widget for my home screen an apparently this doesn't do that-", "Solid app for years! Been noticing prices not updating sometimes, but I suspect the issue being with the api requests and not the app itself.", "Widgets not working correctly, don't update prices from coingecko, though coingecko app works fone Initially I used the pre-processed reviewes, but I wanted ChatGPT to analyze the whole review in its original state for a more accurate sentiment analysis. I also asked it to base its analysis values on the same scale that vader and textblob use, where -1 is negative, 0 is neutral, and 1 is positive. I did this so I can get a more accurate comparison between the ChatGPT's analysis and the ones performed by vader and textblob. 

b) I noticed that compared to the textblob result, ChatGPT's sentiment analysis was completely different about half the time, and often times textblob would determine the sentiment of a review to be 0.0 or neutral, where as ChatGPT would determine it to be negative. I believe this discrepency stems from the fact that I used the original reviews for ChatGPT's sentiment analysis, but the pre-processed reviews for textblob. ChatGPT is able to more accurately represent the original reviews sentiment because it is able to see the review in its whole, as opposed to just the key words taken from it. For example the last review textblob determined as neutral, however when reading the original review it is clear that the review was meant to be taken with a slight negative tone to it, which ChatGPT correctly analyzed. 

c) Vader's sentiment analysis is on average closer to ChatGPT's sentiment analysis, although a similar issue we see with textblob is still present, where, due to the pre-processed review being too different from the original, some reviews that vader determines to be positive or negative are deemed the opposite in ChatGPT's analysis. On average I would still say ChatGPT offers a more accurate sentiment analysis when compared to textblob and vader. .".